services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: RASPLUS
      MYSQL_USER: rasmoo
      MYSQL_PASSWORD: senha123
    volumes:
      - mysql_data_container:/data/db
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: rasmoo
      MONGO_INITDB_ROOT_PASSWORD: senha123
    volumes:
      - mongo_data_container:/data/db
volumes:
  mysql_data_container:
  mongo_data_container: