#api
server:
  servlet:
    context-path: /ws-ras
  port: ${SERVER_PORT:5000}
#bd
spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/RASPLUS}
    username: ${MYSQL_USERNAME:admin}
    password: ${MYSQL_PASSWORD:Qwe123!123}
  jpa:
    properties:
      hibernate:
        show_sql: true
        #format_sql: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  #Swagger
  springdoc:
    swagger-ui:
    path: /swagger-ui.html
  #gmail
  mail:
    host: smtp.gmail.com
    port: 587
    username: carlosdavi090787@gmail.com
    password: wbjsidbqlwtnxhwt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

# Configuração do cliente Feign
ws-ras:
  name: ws-ras
  url: https://ws-raspay.herokuapp.com/ws-raspay/v1
ws-secret:
  name: secret
  defaultPass: qwe123
  #expiration quantidade de days
  expiration: 3
swagger-security:
          /api/v1/auth/**,
          "/v2/api-docs",
          "/v3/api-docs",
          "/v3/api-docs/**",
          "/swagger-resources",
          "/swagger-resources/**",
          "/configuration/ui",
          "/configuration/security",
          "/swagger-ui/**",
          "/webjars/**",
          "/swagger-ui.html"

#@Value("#{'${swagger-security}'.split(',')}")
  #    private List<String> urls;

